server:
  port: 9090
spring:
  application:
    name: Client-Server
  security:
    oauth2:
      client:
        registration:
          taco-admin-client:
            provider: messangercloud
            client-id: messanger-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/messanger-admin-client"
            scope: chats,profil,openid
        provider:
          messangercloud:
            issuer-uri: http://authServ:9000
            authorization-uri: http://authServ:9000/oauth2/authorize
            token-uri: http://authServ:9000/oauth2/token
            jwk-set-uri: http://authServ:9000/oauth2/jwks
            user-info-uri: http://authServ:9000/userinfo
            user-name-attribute: sub